version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    command: sh -c "rabbitmq-plugins enable rabbitmq_management; rabbitmq-server"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
      
  pixel-serivse:
    image: 'pixel-serivse'
    build:
      context: .
      dockerfile: VisitorsTracker.Pixel\Dockerfile

  storge-service:
    image: 'storge-service'
    build:
      context: .
      dockerfile: VisitorsTracker.Storage\Dockerfile